name: "Check"

on:
  pull_request:

jobs:
  checks:
    name: "Check"
    runs-on: "ubuntu-slim"

    permissions:
      contents: "read"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v7.0.1"

      - name: "Check scripts"
        run: "shellcheck .github/scripts/*.sh"

      - name: "Check content"
        run: "bash .github/scripts/generate.sh"
