name: "Pull Request"

on:
  pull_request:

jobs:
  checks:
    name: "Run checks"
    runs-on: "ubuntu-slim"

    permissions:
      contents: "read"

    steps:
      - name: "Checkout the source code"
        uses: "actions/checkout@v7.0.1"

      - name: "Check scripts"
        run: "shellcheck .github/scripts/*.sh"

      - name: "Generate content"
        run: "bash .github/scripts/generate.sh"
